import api from './api';
import { SORT, SECTIONS, WINDOW } from '../utils/constants';

function getGalleryImages(section = SECTIONS.HOT, sort = SORT.VIRAL, window = WINDOW.DAY, showViral = true) { // default values by the API
  // return api.get(`https://api.imgur.com/3/gallery/${section}/${sort}/0.json?showViral=${showViral}`);
  // return api.get('https://api.imgur.com/3/gallery/hot/viral');
  return {
    data: [  
    {
        "id": "VCjGXDP",
        "title": "its all connected",
        "description": null,
        "datetime": 1678800134,
        "cover": "pd5W7QI",
        "cover_width": 720,
        "cover_height": 892,
        "account_url": "roanhouse",
        "account_id": 184797,
        "privacy": "hidden",
        "layout": "blog",
        "views": 37759,
        "link": "https://imgur.com/a/VCjGXDP",
        "ups": 1110,
        "downs": 21,
        "points": 1089,
        "score": 1107,
        "is_album": true,
        "vote": null,
        "favorite": false,
        "nsfw": false,
        "section": "",
        "comment_count": 85,
        "favorite_count": 78,
        "topic": null,
        "topic_id": null,
        "images_count": 1,
        "in_gallery": true,
        "is_ad": false,
        "tags": [],
        "ad_type": 0,
        "ad_url": "",
        "in_most_viral": true,
        "include_album_ads": false,
        "images": [
            {
                "id": "pd5W7QI",
                "title": null,
                "description": null,
                "datetime": 1678800122,
                "type": "image/jpeg",
                "animated": false,
                "width": 720,
                "height": 892,
                "size": 58100,
                "views": 20277,
                "bandwidth": 1178093700,
                "vote": null,
                "favorite": false,
                "nsfw": null,
                "section": null,
                "account_url": null,
                "account_id": null,
                "is_ad": false,
                "in_most_viral": false,
                "has_sound": false,
                "tags": [],
                "ad_type": 0,
                "ad_url": "",
                "edited": "0",
                "in_gallery": false,
                "link": "https://i.imgur.com/pd5W7QI.jpg",
                "comment_count": null,
                "favorite_count": null,
                "ups": null,
                "downs": null,
                "points": null,
                "score": null
            }
        ],
        "ad_config": {
            "safeFlags": [
                "album",
                "in_gallery",
                "sixth_mod_safe",
                "gallery"
            ],
            "highRiskFlags": [],
            "unsafeFlags": [],
            "wallUnsafeFlags": [],
            "showsAds": true,
            "showAdLevel": 2,
            "safe_flags": [
                "album",
                "in_gallery",
                "sixth_mod_safe",
                "gallery"
            ],
            "high_risk_flags": [],
            "unsafe_flags": [],
            "wall_unsafe_flags": [],
            "show_ads": true,
            "show_ad_level": 2,
            "nsfw_score": 0.1
        }
    },
    {
        "id": "Mt91Nyq",
        "title": "Save the Children",
        "description": null,
        "datetime": 1678801374,
        "cover": "9DxEPAJ",
        "cover_width": 780,
        "cover_height": 602,
        "account_url": "darkpoetza",
        "account_id": 780042,
        "privacy": "hidden",
        "layout": "blog",
        "views": 31633,
        "link": "https://imgur.com/a/Mt91Nyq",
        "ups": 999,
        "downs": 22,
        "points": 977,
        "score": 992,
        "is_album": true,
        "vote": null,
        "favorite": false,
        "nsfw": false,
        "section": "",
        "comment_count": 58,
        "favorite_count": 120,
        "topic": null,
        "topic_id": null,
        "images_count": 1,
        "in_gallery": true,
        "is_ad": false,
        "tags": [
            {
                "name": "politics",
                "display_name": "politics",
                "followers": 37199,
                "total_items": 96534,
                "following": false,
                "is_whitelisted": false,
                "background_hash": "hY7ienv",
                "thumbnail_hash": null,
                "accent": "45859C",
                "background_is_animated": false,
                "thumbnail_is_animated": false,
                "is_promoted": false,
                "description": "",
                "logo_hash": null,
                "logo_destination_url": null,
                "description_annotations": {}
            }
        ],
        "ad_type": 0,
        "ad_url": "",
        "in_most_viral": true,
        "include_album_ads": false,
        "images": [
            {
                "id": "9DxEPAJ",
                "title": null,
                "description": null,
                "datetime": 1678801300,
                "type": "image/png",
                "animated": false,
                "width": 780,
                "height": 602,
                "size": 439151,
                "views": 15373,
                "bandwidth": 6751068323,
                "vote": null,
                "favorite": false,
                "nsfw": null,
                "section": null,
                "account_url": null,
                "account_id": null,
                "is_ad": false,
                "in_most_viral": false,
                "has_sound": false,
                "tags": [],
                "ad_type": 0,
                "ad_url": "",
                "edited": "0",
                "in_gallery": false,
                "link": "https://i.imgur.com/9DxEPAJ.png",
                "comment_count": null,
                "favorite_count": null,
                "ups": null,
                "downs": null,
                "points": null,
                "score": null
            }
        ],
        "ad_config": {
            "safeFlags": [
                "album",
                "in_gallery",
                "sixth_mod_safe",
                "gallery"
            ],
            "highRiskFlags": [],
            "unsafeFlags": [],
            "wallUnsafeFlags": [],
            "showsAds": true,
            "showAdLevel": 2,
            "safe_flags": [
                "album",
                "in_gallery",
                "sixth_mod_safe",
                "gallery"
            ],
            "high_risk_flags": [],
            "unsafe_flags": [],
            "wall_unsafe_flags": [],
            "show_ads": true,
            "show_ad_level": 2,
            "nsfw_score": 0
        }
    },
    {
        "id": "R7P2YZr",
        "title": "One mini-dump coming right up",
        "description": 'a very very very very very very koasdasdndasijdsajidsajidsajidsaijdsaijdsajidsajisajdijisdaji jaidjsijdasjaids jdjasjidaj asdiajsdjaisjidasjidasjidsjiasij',
        "datetime": 1678800494,
        "cover": "ExECUwh",
        "cover_width": 1000,
        "cover_height": 1000,
        "account_url": "trustfallaccident",
        "account_id": 145014435,
        "privacy": "hidden",
        "layout": "blog",
        "views": 43088,
        "link": "https://imgur.com/a/R7P2YZr",
        "ups": 871,
        "downs": 17,
        "points": 854,
        "score": 875,
        "is_album": true,
        "vote": null,
        "favorite": false,
        "nsfw": false,
        "section": "",
        "comment_count": 65,
        "favorite_count": 102,
        "topic": null,
        "topic_id": null,
        "images_count": 11,
        "in_gallery": true,
        "is_ad": false,
        "tags": [
            {
                "name": "meme",
                "display_name": "meme",
                "followers": 140761,
                "total_items": 90379,
                "following": false,
                "is_whitelisted": false,
                "background_hash": "1fDftsZ",
                "thumbnail_hash": null,
                "accent": "ba519f",
                "background_is_animated": false,
                "thumbnail_is_animated": false,
                "is_promoted": false,
                "description": "",
                "logo_hash": null,
                "logo_destination_url": null,
                "description_annotations": {}
            },
            {
                "name": "memes",
                "display_name": "memes",
                "followers": 2801149,
                "total_items": 577291,
                "following": false,
                "is_whitelisted": false,
                "background_hash": "1z4dgZT",
                "thumbnail_hash": null,
                "accent": "ba519f",
                "background_is_animated": false,
                "thumbnail_is_animated": false,
                "is_promoted": false,
                "description": "the freshest memes",
                "logo_hash": null,
                "logo_destination_url": null,
                "description_annotations": {}
            },
            {
                "name": "mildly_amusing",
                "display_name": "mildly amusing",
                "followers": 10127,
                "total_items": 12307,
                "following": false,
                "is_whitelisted": false,
                "background_hash": "A2MU7EC",
                "thumbnail_hash": null,
                "accent": "50535A",
                "background_is_animated": false,
                "thumbnail_is_animated": false,
                "is_promoted": false,
                "description": "",
                "logo_hash": null,
                "logo_destination_url": null,
                "description_annotations": {}
            },
            {
                "name": "mildly_interesting",
                "display_name": "mildly interesting",
                "followers": 135670,
                "total_items": 94245,
                "following": false,
                "is_whitelisted": false,
                "background_hash": "oAtvuB2",
                "thumbnail_hash": null,
                "accent": "16A943",
                "background_is_animated": false,
                "thumbnail_is_animated": false,
                "is_promoted": false,
                "description": "Things to make you go \"hmm.\" ",
                "logo_hash": null,
                "logo_destination_url": null,
                "description_annotations": {}
            },
            {
                "name": "dump",
                "display_name": "dump",
                "followers": 95459,
                "total_items": 61098,
                "following": false,
                "is_whitelisted": false,
                "background_hash": "gbuk2AN",
                "thumbnail_hash": null,
                "accent": null,
                "background_is_animated": false,
                "thumbnail_is_animated": false,
                "is_promoted": false,
                "description": "",
                "logo_hash": null,
                "logo_destination_url": null,
                "description_annotations": {}
            }
        ],
        "ad_type": 0,
        "ad_url": "",
        "in_most_viral": true,
        "include_album_ads": false,
        "images": [
            {
                "id": "ExECUwh",
                "title": null,
                "description": "1",
                "datetime": 1678795909,
                "type": "image/jpeg",
                "animated": false,
                "width": 1000,
                "height": 1000,
                "size": 91351,
                "views": 21549,
                "bandwidth": 1968522699,
                "vote": null,
                "favorite": false,
                "nsfw": null,
                "section": null,
                "account_url": null,
                "account_id": null,
                "is_ad": false,
                "in_most_viral": false,
                "has_sound": false,
                "tags": [],
                "ad_type": 0,
                "ad_url": "",
                "edited": "0",
                "in_gallery": false,
                "link": "https://i.imgur.com/ExECUwh.jpg",
                "comment_count": null,
                "favorite_count": null,
                "ups": null,
                "downs": null,
                "points": null,
                "score": null
            },
            {
                "id": "JYjT0wh",
                "title": null,
                "description": "2",
                "datetime": 1678800170,
                "type": "image/jpeg",
                "animated": false,
                "width": 537,
                "height": 678,
                "size": 22544,
                "views": 15708,
                "bandwidth": 354121152,
                "vote": null,
                "favorite": false,
                "nsfw": null,
                "section": null,
                "account_url": null,
                "account_id": null,
                "is_ad": false,
                "in_most_viral": false,
                "has_sound": false,
                "tags": [],
                "ad_type": 0,
                "ad_url": "",
                "edited": "0",
                "in_gallery": false,
                "link": "https://i.imgur.com/JYjT0wh.jpg",
                "comment_count": null,
                "favorite_count": null,
                "ups": null,
                "downs": null,
                "points": null,
                "score": null
            },
            {
                "id": "RgTElZV",
                "title": null,
                "description": "3",
                "datetime": 1678795903,
                "type": "image/jpeg",
                "animated": false,
                "width": 591,
                "height": 645,
                "size": 45716,
                "views": 11651,
                "bandwidth": 532637116,
                "vote": null,
                "favorite": false,
                "nsfw": null,
                "section": null,
                "account_url": null,
                "account_id": null,
                "is_ad": false,
                "in_most_viral": false,
                "has_sound": false,
                "tags": [],
                "ad_type": 0,
                "ad_url": "",
                "edited": "0",
                "in_gallery": false,
                "link": "https://i.imgur.com/RgTElZV.jpg",
                "comment_count": null,
                "favorite_count": null,
                "ups": null,
                "downs": null,
                "points": null,
                "score": null
            }
        ],
        "ad_config": {
            "safeFlags": [
                "album",
                "in_gallery",
                "sixth_mod_safe",
                "gallery"
            ],
            "highRiskFlags": [],
            "unsafeFlags": [],
            "wallUnsafeFlags": [],
            "showsAds": true,
            "showAdLevel": 2,
            "safe_flags": [
                "album",
                "in_gallery",
                "sixth_mod_safe",
                "gallery"
            ],
            "high_risk_flags": [],
            "unsafe_flags": [],
            "wall_unsafe_flags": [],
            "show_ads": true,
            "show_ad_level": 2,
            "nsfw_score": 0
        }
    },
    {
        "id": "J7rbVvD",
        "title": "New(ish) Pocketsss Comics!",
        "description": null,
        "datetime": 1678802806,
        "cover": "UMLy1bc",
        "cover_width": 1378,
        "cover_height": 2048,
        "account_url": "unit117jax",
        "account_id": 96922425,
        "privacy": "hidden",
        "layout": "blog",
        "views": 30362,
        "link": "https://imgur.com/a/J7rbVvD",
        "ups": 761,
        "downs": 8,
        "points": 753,
        "score": 768,
        "is_album": true,
        "vote": null,
        "favorite": false,
        "nsfw": false,
        "section": "",
        "comment_count": 49,
        "favorite_count": 308,
        "topic": null,
        "topic_id": null,
        "images_count": 11,
        "in_gallery": true,
        "is_ad": false,
        "tags": [
            {
                "name": "webcomic",
                "display_name": "webcomic",
                "followers": 22543,
                "total_items": 28798,
                "following": false,
                "is_whitelisted": false,
                "background_hash": "f8B0kEw",
                "thumbnail_hash": null,
                "accent": "5B62A5",
                "background_is_animated": false,
                "thumbnail_is_animated": false,
                "is_promoted": false,
                "description": "",
                "logo_hash": null,
                "logo_destination_url": null,
                "description_annotations": {}
            },
            {
                "name": "goblin",
                "display_name": "goblin",
                "followers": 231,
                "total_items": 580,
                "following": false,
                "is_whitelisted": false,
                "background_hash": "QL9pTeJ",
                "thumbnail_hash": null,
                "accent": "159559",
                "background_is_animated": false,
                "thumbnail_is_animated": false,
                "is_promoted": false,
                "description": "",
                "logo_hash": null,
                "logo_destination_url": null,
                "description_annotations": {}
            }
        ],
        "ad_type": 0,
        "ad_url": "",
        "in_most_viral": true,
        "include_album_ads": false,
        "images": [
            {
                "id": "UMLy1bc",
                "title": null,
                "description": null,
                "datetime": 1678802662,
                "type": "image/jpeg",
                "animated": false,
                "width": 1378,
                "height": 2048,
                "size": 411187,
                "views": 13437,
                "bandwidth": 5525119719,
                "vote": null,
                "favorite": false,
                "nsfw": null,
                "section": null,
                "account_url": null,
                "account_id": null,
                "is_ad": false,
                "in_most_viral": false,
                "has_sound": false,
                "tags": [],
                "ad_type": 0,
                "ad_url": "",
                "edited": "0",
                "in_gallery": false,
                "link": "https://i.imgur.com/UMLy1bc.jpg",
                "comment_count": null,
                "favorite_count": null,
                "ups": null,
                "downs": null,
                "points": null,
                "score": null
            },
          ],
    },
  ]};
}

export {
  getGalleryImages,
}
